### ISSUE TITLE
3.11 和 最新自动build 在windowns 或 centos 上都出现以下错误，怎么解决啊

### ISSUE THREAD

**Issue by lindent** [godcong/fate#65]
`config loaded: &{RunInit:false FilterMode:0 StrokeMax:18 StrokeMin:3 HardFilter:false FixBazi:false SupplyFilter:true ZodiacFilter:true BaguaFilter:true Regular:true Database:{Host:***** Port:3306 User:fate Pwd:**** Name:fate MaxIdleCon:0 MaxOpenCon:0 Driver:mysql File: Dsn: ShowSQL:false ShowExecTime:false} FileOutput:{OutputMode:0 Path:name.txt Heads:[姓名 笔画 拼音 喜用神 八字]}}{"level":"info","ts":1592041181.400563,"caller":"fate/fate.go:133","msg":"正在使用Fate生成姓名列表，如遇到问题请访问项目地址：https://github.com/godcong/fate获取帮助!"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x8a3685]

goroutine 1 [running]:
github.com/godcong/fate.(*Zodiac).zodiacJi(...)
        D:/workspace/golang/project/fate/zodiac.go:48
github.com/godcong/fate.(*Zodiac).Point(0x0, 0xc0003cd900, 0x0)
        D:/workspace/golang/project/fate/zodiac.go:71 +0x65
github.com/godcong/fate.(*Zodiac).PointCheck(0x0, 0x3, 0xc0003d2b90, 0x2, 0x2, 0x1)
        D:/workspace/golang/project/fate/zodiac.go:61 +0x57
github.com/godcong/fate.filterZodiac(0xa93680, 0xc0000b1920, 0xc0003d2b90, 0x2, 0x2, 0x1)
        D:/workspace/golang/project/fate/zodiac.go:55 +0x6a
github.com/godcong/fate.(*fateImpl).MakeName(0xc0000de790, 0xa95740, 0xc0000ba048, 0xed20a4d7c, 0x0)
        D:/workspace/golang/project/fate/fate.go:177 +0x16d6
main.cmdName.func1(0xc0000c8c80, 0xc0000c16c0, 0x0, 0x4)
        D:/workspace/golang/project/fate/cmd/console/name.go:32 +0x2f9
github.com/spf13/cobra.(*Command).execute(0xc0000c8c80, 0xc0000c1640, 0x4, 0x4, 0xc0000c8c80, 0xc0000c1640)
        D:/workspace/golang/path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xe045e0, 0xc00008ff40, 0x2, 0x2)
        D:/workspace/golang/path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        D:/workspace/golang/path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        D:/workspace/golang/project/fate/cmd/console/main.go:21 +0x8b
`

**Comment by godcong** [comment]
是什么生肖？

**Comment by housemecn** [comment]
属马的也报错了！！！

**Comment by godcong** [comment]
> 属马的也报错了！！！

没有马，马的资料还没整理好
