### ISSUE TITLE
[BUG]时间选择有问题

### ISSUE THREAD

**Issue by Aquarian-Age** [godcong/fate#69]
### 可以正确运行的

```
~/nfs_share/golang/fate/auto_build
liangzi@xuan 74 12:47 >./fate_linux_amd64 name -l 梁 -b "2020/02/06 15:04"

```

### 不能正确运行的

./fate_linux_amd64 name -l 梁 -b "1981/02/06 12:04"    
```bash
start 2020-07-01 12:47:57.4202612 +0800 CST m=+0.003559617
config loaded: &{RunInit:false FilterMode:0 StrokeMax:18 StrokeMin:3 HardFilter:false FixBazi:false SupplyFilter:true ZodiacFilter:true BaguaFilter:true Regular:true Database:{Host:127.0.0.1 Port:3306 User:root Pwd:xxxxx Name:fate MaxIdleCon:0 MaxOpenCon:0 Driver:mysql File: Dsn: ShowSQL:false ShowExecTime:false} FileOutput:{OutputMode:0 Path:name.txt Heads:[姓名 笔画 拼音 喜用神 八字]}}{"level":"info","ts":1593578877.4218926,"caller":"fate/fate.go:137","msg":"正在使用Fate生成姓名列表，如遇到问题请访问项目地址：https://github.com/godcong/fate获取帮助!"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x8ab1b5]

goroutine 1 [running]:
github.com/godcong/fate.(*Zodiac).zodiacJi(...)
        /home/runner/work/fate/fate/zodiac.go:67
github.com/godcong/fate.(*Zodiac).Point(0x0, 0xc000325e00, 0x0)
        /home/runner/work/fate/fate/zodiac.go:90 +0x65
github.com/godcong/fate.(*Zodiac).PointCheck(0x0, 0x3, 0xc000364af0, 0x2, 0x2, 0x1)
        /home/runner/work/fate/fate/zodiac.go:80 +0x57
github.com/godcong/fate.filterZodiac(0xa9bee0, 0xc0000a9940, 0xc000364af0, 0x2, 0x2, 0x1)
        /home/runner/work/fate/fate/zodiac.go:74 +0x6a
github.com/godcong/fate.(*fateImpl).MakeName(0xc0000da840, 0xa9df20, 0xc0000b4038, 0xe8c2eb3b0, 0x0)
        /home/runner/work/fate/fate/fate.go:181 +0x16d6
main.cmdName.func1(0xc0000c4c80, 0xc0000dd680, 0x0, 0x4)
        /home/runner/work/fate/fate/cmd/console/name.go:40 +0x4b2
github.com/spf13/cobra.(*Command).execute(0xc0000c4c80, 0xc0000dd600, 0x4, 0x4, 0xc0000c4c80, 0xc0000dd600)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xe108a0, 0xc0000e5f40, 0x2, 0x2)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /home/runner/work/fate/fate/cmd/console/main.go:21 +0x8b

```

**Comment by godcong** [comment]
这是对应的生肖资料还没有整理添加的关系.
生肖已经加了,但没有资料的生肖运行时会显示警告.

**Comment by Aquarian-Age** [comment]
> 这是对应的生肖资料还没有整理添加的关系.
> 生肖已经加了,但没有资料的生肖运行时会显示警告.

你说的资料没有整理添加　是指的下面false的部分吗？
```go

var zodiacSupportList = map[string]bool{
	ZodiacRat:     true,
	ZodiacCow:     true,
	ZodiacTiger:   false,
	ZodiacRabbit:  false,
	ZodiacDragon:  false,
	ZodiacSnake:   false,
	ZodiacHorse:   false,
	ZodiacSheep:   false,
	ZodiacMonkey:  false,
	ZodiacChicken: false,
	ZodiacDog:     false,
	ZodiacPig:     true,
}
```
另外 auto_build的源码方便提供吗？谢谢

**Comment by godcong** [comment]
是的，false没有过滤生肖字。

auto build 没有源码啊，只有一个yml，在.github下面，你点进去就能看到了

**Comment by Aquarian-Age** [comment]
> 是的，false没有过滤生肖字。
> 
> auto build 没有源码啊，只有一个yml，在.github下面，你点进去就能看到了

----------

这方面还有计划过滤生肖字吗？改天我看看源码
